export const VERDICTS = Object.freeze({
  ACCEPTED: 'ACCEPTED',
  WRONG_ANSWER: 'WRONG_ANSWER',
  RUNTIME_ERROR: 'RUNTIME_ERROR',
  TIME_LIMIT_EXCEEDED: 'TIME_LIMIT_EXCEEDED',
  COMPILATION_ERROR: 'COMPILATION_ERROR',
  PENDING: 'PENDING',
  CHEATER_DETECTED: 'VERDICT_PENDING: CHEATER DETECTED',
});

export const PROBLEMS = Object.freeze({
  A: {
    id: 'A',
    title: 'Find sum of two integers.',
    timeLimitMs: 1000,
    memoryLimitMb: 256,
    checker: 'sum',
  },
});

export const CF_VERDICT_MAP = Object.freeze({
  OK: VERDICTS.ACCEPTED,
  WRONG_ANSWER: VERDICTS.WRONG_ANSWER,
  RUNTIME_ERROR: VERDICTS.RUNTIME_ERROR,
  TIME_LIMIT_EXCEEDED: VERDICTS.TIME_LIMIT_EXCEEDED,
  COMPILATION_ERROR: VERDICTS.COMPILATION_ERROR,
  MEMORY_LIMIT_EXCEEDED: VERDICTS.RUNTIME_ERROR,
  PRESENTATION_ERROR: VERDICTS.WRONG_ANSWER,
  IDLENESS_LIMIT_EXCEEDED: VERDICTS.TIME_LIMIT_EXCEEDED,
  SECURITY_VIOLATED: VERDICTS.RUNTIME_ERROR,
  CRASHED: VERDICTS.RUNTIME_ERROR,
  CHALLENGED: VERDICTS.WRONG_ANSWER,
  SKIPPED: VERDICTS.WRONG_ANSWER,
  TESTING: VERDICTS.PENDING,
  REJECTED: VERDICTS.WRONG_ANSWER,
});
